version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: classicpress
      MYSQL_USER: classicpress
      MYSQL_PASSWORD: classicpress

  classicpress:
    depends_on:
      - db
    image: classicpress/classicpress:latest
    ports:
      - "3030:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: classicpress
      WORDPRESS_DB_PASSWORD: classicpress
      WORDPRESS_DB_NAME: classicpress
    volumes:
      - ./wp_data:/var/www/html

volumes:
  db_data:
  wp_data:
